input-training: [../data/zedcam_F/train/seg+resize]
label-training: ../data/zedcam_F/train/bev+occlusion+rotation
max-samples-training: 100000
input-validation: [../data/zedcam_F/val/front+resize]
label-validation: ../data/zedcam_F/val/bev+occlusion+rotation
max-samples-validation: 10000

image-shape: [256, 512]
one-hot-palette-input: one_hot_conversion/convert_10_carla.xml
one-hot-palette-label: one_hot_conversion/convert_3+occl_carla.xml

model: architecture/uNetXST.py
unetxst-homographies: ../preprocessing/homography_converter/uNetXST_homographies/zedcam_F.py
epochs: 100
batch-size: 5
learning-rate: 1e-4
loss-weights: [0.34880363, 2.72646122, 3.64849884, 1.59461004]
early-stopping-patience: 100 # 20

save-interval: 5
output-dir: output

# for training continuation, evaluation and prediction only
class-names: [road, obstacle, lane line, occluded]
# model-weights:

# for predict.py only
input-testing: [../data/zedcam_F/no_mans_land]
max-samples-testing: 1000
# prediction-dir:
